INSERT INTO CA_PRINCIPAL (ID, NAME, PRINCIPAL_TYPE, LOCKED)
VALUES(1, 'admin', 0, 0);
INSERT INTO CA_USER (ID, REALNAME, PASSWORD)
VALUES(1, 'ADMINISTRATOR', 'ABC123');

INSERT INTO CA_PRINCIPAL (ID, NAME, PRINCIPAL_TYPE, LOCKED)
VALUES(2, 'group_admin', 0, 0);
INSERT INTO CA_GROUP (ID)
VALUES(2);
