-- ====================================================================================================
-- DOCUMENTS
-- ====================================================================================================

DROP TABLE CA_ITEM_PRICE_LEVEL CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_ITEM_PRICE_LEVEL;
DROP TABLE CA_ITEM CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_ITEM;

DROP TABLE CA_SALES_INVOICE_ITEM CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_SALES_INVOICE_ITEM;
DROP TABLE CA_SALES_INVOICE CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_SALES_INVOICE;
DROP TABLE CA_SALES_ORDER_ITEM CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_SALES_ORDER_ITEM;
DROP TABLE CA_SALES_ORDER CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_SALES_ORDER;

DROP TABLE CA_PURCHASE_INVOICE_ITEM CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_PURCHASE_INVOICE_ITEM;
DROP TABLE CA_PURCHASE_INVOICE CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_PURCHASE_INVOICE;
DROP TABLE CA_PURCHASE_ORDER_ITEM CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_PURCHASE_ORDER_ITEM;
DROP TABLE CA_PURCHASE_ORDER CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_PURCHASE_ORDER;

DROP TABLE CA_DOCUMENT CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_DOCUMENT;

-- ====================================================================================================
-- DATA DICTIONARY
-- ====================================================================================================

DROP TABLE CA_ITEM_PRICE CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_ITEM_PRICE;
DROP TABLE CA_ITEM CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_ITEM;

DROP TABLE CA_SALESPERSON CASCADE CONSTRAINTS PURGE;
DROP TABLE CA_VENDOR CASCADE CONSTRAINTS PURGE;
DROP TABLE CA_CUSTOMER CASCADE CONSTRAINTS PURGE;
DROP TABLE CA_CONSUMER CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_CONSUMER;

DROP TABLE CA_POSTING CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_POSTING;
DROP TABLE CA_JOURNAL CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_JOURNAL;

DROP TABLE CA_ITEM_CODE CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_ITEM_CODE;
DROP TABLE CA_SITE_CODE CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_SITE_CODE;
DROP TABLE CA_UNIT_CODE CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_UNIT_CODE;

DROP TABLE CA_ACCOUNT CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_ACCOUNT;
DROP TABLE CA_ACCOUNT_CODE CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_ACCOUNT_CODE;
DROP TABLE CA_PROJECT_CODE CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_PROJECT_CODE;
DROP TABLE CA_DEPARTMENT_CODE CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_DEPARTMENT_CODE;

DROP TABLE CA_GROUP CASCADE CONSTRAINTS PURGE;
DROP TABLE CA_USER CASCADE CONSTRAINTS PURGE;
DROP TABLE CA_PRINCIPAL CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_CA_PRINCIPAL;
